import { useEffect, useState, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Sparkles, BookOpen, Layers, FileText, CheckCircle2 } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { cn } from "@/lib/utils";

interface AIGenerationLoadingDialogProps {
  open: boolean;
  courseTitle: string;
  onComplete: () => void;
}

const GENERATION_STEPS = [
  { icon: Sparkles, label: "Analyzing course intent...", duration: 1200 },
  { icon: Layers, label: "Building course structure...", duration: 1400 },
  { icon: FileText, label: "Generating content blocks...", duration: 1600 },
  { icon: BookOpen, label: "Assembling your course...", duration: 1000 },
];

export function AIGenerationLoadingDialog({ open, courseTitle, onComplete }: AIGenerationLoadingDialogProps) {
  const [progress, setProgress] = useState(0);
  const [activeStep, setActiveStep] = useState(0);
  const [completed, setCompleted] = useState(false);

  const totalDuration = GENERATION_STEPS.reduce((sum, s) => sum + s.duration, 0);

  const stableOnComplete = useCallback(onComplete, [onComplete]);

  useEffect(() => {
    if (!open) {
      setProgress(0);
      setActiveStep(0);
      setCompleted(false);
      return;
    }

    const startTime = Date.now();
    const progressInterval = setInterval(() => {
      const elapsed = Date.now() - startTime;
      const pct = Math.min((elapsed / totalDuration) * 100, 100);
      setProgress(pct);

      // Determine active step
      let accumulated = 0;
      for (let i = 0; i < GENERATION_STEPS.length; i++) {
        accumulated += GENERATION_STEPS[i].duration;
        if (elapsed < accumulated) {
          setActiveStep(i);
          break;
        }
        if (i === GENERATION_STEPS.length - 1) {
          setActiveStep(i);
        }
      }

      if (pct >= 100) {
        clearInterval(progressInterval);
        setCompleted(true);
        setTimeout(() => stableOnComplete(), 800);
      }
    }, 50);

    return () => clearInterval(progressInterval);
  }, [open, totalDuration, stableOnComplete]);

  return (
    <Dialog open={open}>
      <DialogContent
        className="sm:max-w-md p-0 gap-0 overflow-hidden border-0 shadow-2xl [&>button]:hidden"
        onPointerDownOutside={(e) => e.preventDefault()}
        onEscapeKeyDown={(e) => e.preventDefault()}
      >
        <DialogTitle className="sr-only">Generating AI Course</DialogTitle>
        <DialogDescription className="sr-only">
          Please wait while your course is being generated by AI.
        </DialogDescription>

        {/* Animated gradient header strip */}
        <div className="relative h-2 w-full overflow-hidden bg-muted" aria-hidden="true">
          <motion.div
            className="absolute inset-y-0 left-0 rounded-r-full"
            style={{
              background: "linear-gradient(90deg, hsl(var(--primary)), hsl(270 80% 55%), hsl(var(--primary)))",
              backgroundSize: "200% 100%",
            }}
            animate={{
              width: `${progress}%`,
              backgroundPosition: ["0% 0%", "100% 0%", "0% 0%"],
            }}
            transition={{
              width: { duration: 0.3, ease: "easeOut" },
              backgroundPosition: { duration: 2, repeat: Infinity, ease: "linear" },
            }}
          />
        </div>

        <div className="px-8 pt-8 pb-6 flex flex-col items-center text-center">
          {/* Animated orb */}
          <div className="relative mb-6">
            {/* Outer rotating ring */}
            <motion.div
              className="absolute inset-[-8px] rounded-full border-2 border-dashed border-primary/30"
              animate={{ rotate: 360 }}
              transition={{ duration: 8, repeat: Infinity, ease: "linear" }}
              aria-hidden="true"
            />
            {/* Middle pulsing ring */}
            <motion.div
              className="absolute inset-[-4px] rounded-full border border-primary/20"
              animate={{ scale: [1, 1.1, 1], opacity: [0.3, 0.6, 0.3] }}
              transition={{ duration: 2, repeat: Infinity, ease: "easeInOut" }}
              aria-hidden="true"
            />
            {/* Core icon */}
            <motion.div
              className={cn(
                "w-16 h-16 rounded-full flex items-center justify-center",
                "bg-gradient-to-br from-primary to-[hsl(270_80%_55%)]"
              )}
              animate={completed ? { scale: [1, 1.15, 1] } : { scale: [1, 1.05, 1] }}
              transition={{ duration: completed ? 0.4 : 2, repeat: completed ? 0 : Infinity, ease: "easeInOut" }}
            >
              <AnimatePresence mode="wait">
                {completed ? (
                  <motion.div
                    key="check"
                    initial={{ scale: 0, rotate: -90 }}
                    animate={{ scale: 1, rotate: 0 }}
                    transition={{ type: "spring", stiffness: 300, damping: 15 }}
                  >
                    <CheckCircle2 className="w-7 h-7 text-primary-foreground" aria-hidden="true" focusable="false" />
                  </motion.div>
                ) : (
                  <motion.div
                    key="sparkle"
                    animate={{ rotate: [0, 10, -10, 0] }}
                    transition={{ duration: 3, repeat: Infinity, ease: "easeInOut" }}
                  >
                    <Sparkles className="w-7 h-7 text-primary-foreground" aria-hidden="true" focusable="false" />
                  </motion.div>
                )}
              </AnimatePresence>
            </motion.div>
          </div>

          {/* Title */}
          <AnimatePresence mode="wait">
            <motion.h3
              key={completed ? "done" : "loading"}
              initial={{ opacity: 0, y: 6 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -6 }}
              className="text-lg font-semibold text-foreground mb-1"
            >
              {completed ? "Course Generated!" : "Generating Your Course"}
            </motion.h3>
          </AnimatePresence>

          <p className="text-sm text-muted-foreground mb-6 max-w-[280px]">
            {completed ? (
              "Redirecting you to the editor..."
            ) : (
              <>
                Creating <span className="font-medium text-foreground">"{courseTitle}"</span> with AI
              </>
            )}
          </p>

          {/* Step list */}
          <div className="w-full space-y-2.5" role="list" aria-label="Generation steps">
            {GENERATION_STEPS.map((step, i) => {
              const StepIcon = step.icon;
              const isDone = i < activeStep || completed;
              const isActive = i === activeStep && !completed;

              return (
                <motion.div
                  key={step.label}
                  role="listitem"
                  initial={{ opacity: 0, x: -12 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: i * 0.1, duration: 0.3 }}
                  className={cn(
                    "flex items-center gap-3 px-4 py-2.5 rounded-lg text-left transition-colors duration-300",
                    isDone && "bg-primary/[0.06]",
                    isActive && "bg-primary/[0.08] border border-primary/15",
                    !isDone && !isActive && "opacity-40"
                  )}
                >
                  <div className={cn(
                    "w-7 h-7 rounded-full flex items-center justify-center shrink-0 transition-colors duration-300",
                    isDone && "bg-primary text-primary-foreground",
                    isActive && "bg-primary/20 text-primary",
                    !isDone && !isActive && "bg-muted text-muted-foreground"
                  )}>
                    {isDone ? (
                      <CheckCircle2 className="w-3.5 h-3.5" aria-hidden="true" focusable="false" />
                    ) : (
                      <StepIcon className={cn("w-3.5 h-3.5", isActive && "animate-pulse")} aria-hidden="true" focusable="false" />
                    )}
                  </div>
                  <span className={cn(
                    "text-sm font-medium transition-colors duration-300",
                    isDone && "text-foreground",
                    isActive && "text-foreground",
                    !isDone && !isActive && "text-muted-foreground"
                  )}>
                    {step.label}
                  </span>
                </motion.div>
              );
            })}
          </div>

          {/* Progress percentage */}
          <div className="mt-4 text-xs text-muted-foreground font-medium tabular-nums">
            {Math.round(progress)}% complete
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
