import { useEffect, useState, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Sparkles, BookOpen, Layers, FileText, CheckCircle2, Clock, GraduationCap } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { cn } from "@/lib/utils";

interface AIGenerationLoadingDialogProps {
  open: boolean;
  courseTitle: string;
  onComplete: () => void;
}

const TICKET_SECTIONS = [
  { title: "Introduction & Overview", pages: 2, icon: BookOpen },
  { title: "Core Concepts", pages: 3, icon: Layers },
  { title: "Deep Dive & Analysis", pages: 3, icon: FileText },
  { title: "Assessment & Wrap-Up", pages: 2, icon: GraduationCap },
];

const STATUS_MESSAGES = [
  "Analyzing course intent...",
  "Building course structure...",
  "Generating content blocks...",
  "Finalizing your course...",
];

export function AIGenerationLoadingDialog({ open, courseTitle, onComplete }: AIGenerationLoadingDialogProps) {
  const [progress, setProgress] = useState(0);
  const [visibleSections, setVisibleSections] = useState(0);
  const [statusIdx, setStatusIdx] = useState(0);
  const [completed, setCompleted] = useState(false);

  const totalDuration = 5200;
  const stableOnComplete = useCallback(onComplete, [onComplete]);

  useEffect(() => {
    if (!open) {
      setProgress(0);
      setVisibleSections(0);
      setStatusIdx(0);
      setCompleted(false);
      return;
    }

    const startTime = Date.now();

    const progressInterval = setInterval(() => {
      const elapsed = Date.now() - startTime;
      const pct = Math.min((elapsed / totalDuration) * 100, 100);
      setProgress(pct);

      const sectionInterval = totalDuration / (TICKET_SECTIONS.length + 1);
      const revealed = Math.min(Math.floor(elapsed / sectionInterval), TICKET_SECTIONS.length);
      setVisibleSections(revealed);

      const msgInterval = totalDuration / STATUS_MESSAGES.length;
      setStatusIdx(Math.min(Math.floor(elapsed / msgInterval), STATUS_MESSAGES.length - 1));

      if (pct >= 100) {
        clearInterval(progressInterval);
        setCompleted(true);
        setTimeout(() => stableOnComplete(), 1000);
      }
    }, 50);

    return () => clearInterval(progressInterval);
  }, [open, stableOnComplete]);

  const totalPages = TICKET_SECTIONS.reduce((s, sec) => s + sec.pages, 0);

  return (
    <Dialog open={open}>
      <DialogContent
        className="sm:max-w-lg p-0 gap-0 overflow-visible border-0 shadow-none [&>button]:hidden bg-transparent max-h-[95vh]"
        onPointerDownOutside={(e) => e.preventDefault()}
        onEscapeKeyDown={(e) => e.preventDefault()}
      >
        <DialogTitle className="sr-only">Generating AI Course</DialogTitle>
        <DialogDescription className="sr-only">
          Please wait while your course is being generated by AI.
        </DialogDescription>

        {/* Rich layered background */}
        <div className="absolute inset-0 -z-10 rounded-2xl overflow-hidden">
          {/* Base gradient */}
          <div
            className="absolute inset-0"
            style={{
              background: "linear-gradient(145deg, hsl(211 60% 16%), hsl(230 40% 12%), hsl(260 35% 14%))",
            }}
            aria-hidden="true"
          />
          {/* Subtle mesh blobs */}
          <motion.div
            className="absolute w-[300px] h-[300px] rounded-full opacity-20 blur-3xl"
            style={{ background: "radial-gradient(circle, hsl(211 100% 50%), transparent 70%)", top: "-40px", left: "-60px" }}
            animate={{ x: [0, 20, 0], y: [0, 15, 0] }}
            transition={{ duration: 8, repeat: Infinity, ease: "easeInOut" }}
            aria-hidden="true"
          />
          <motion.div
            className="absolute w-[250px] h-[250px] rounded-full opacity-15 blur-3xl"
            style={{ background: "radial-gradient(circle, hsl(270 80% 55%), transparent 70%)", bottom: "-30px", right: "-40px" }}
            animate={{ x: [0, -15, 0], y: [0, -20, 0] }}
            transition={{ duration: 10, repeat: Infinity, ease: "easeInOut" }}
            aria-hidden="true"
          />
          {/* Noise texture overlay */}
          <div
            className="absolute inset-0 opacity-[0.03]"
            style={{ backgroundImage: "url(\"data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='1'/%3E%3C/svg%3E\")" }}
            aria-hidden="true"
          />
        </div>

        <div className="flex flex-col items-center py-6 px-4">

          {/* ── Slot Machine Dispenser ── */}
          <div className="relative w-[82%] z-10 mb-0" aria-hidden="true">
            {/* Dispenser housing */}
            <div className="relative h-16 rounded-t-2xl overflow-hidden"
              style={{
                background: "linear-gradient(180deg, hsl(0 0% 75%), hsl(0 0% 60%), hsl(0 0% 68%))",
              }}
            >
              {/* Brushed metal texture */}
              <div className="absolute inset-0 opacity-30"
                style={{
                  background: "repeating-linear-gradient(90deg, transparent, transparent 1px, rgba(255,255,255,0.05) 1px, rgba(255,255,255,0.05) 2px)",
                }}
              />
              {/* Top highlight */}
              <div className="absolute top-0 inset-x-0 h-2 bg-gradient-to-b from-white/30 to-transparent rounded-t-2xl" />
              {/* Bottom inner shadow */}
              <div className="absolute bottom-0 inset-x-0 h-3 bg-gradient-to-t from-black/15 to-transparent" />

              {/* Slot opening */}
              <div className="absolute bottom-0 left-1/2 -translate-x-1/2 w-[72%] h-4">
                <div className="w-full h-full rounded-t-sm"
                  style={{
                    background: "linear-gradient(180deg, hsl(0 0% 20%), hsl(0 0% 30%))",
                    boxShadow: "inset 0 3px 6px rgba(0,0,0,0.4), 0 -1px 0 rgba(255,255,255,0.1)",
                  }}
                />
              </div>

              {/* Decorative screws */}
              <div className="absolute top-3 left-4 w-3 h-3 rounded-full border border-white/20"
                style={{ background: "radial-gradient(circle at 35% 35%, hsl(0 0% 80%), hsl(0 0% 55%))" }}
              />
              <div className="absolute top-3 right-4 w-3 h-3 rounded-full border border-white/20"
                style={{ background: "radial-gradient(circle at 35% 35%, hsl(0 0% 80%), hsl(0 0% 55%))" }}
              />

              {/* Side ridges */}
              <div className="absolute left-2 top-6 bottom-4 w-[3px] rounded-full"
                style={{ background: "linear-gradient(180deg, rgba(255,255,255,0.15), rgba(0,0,0,0.1))" }}
              />
              <div className="absolute right-2 top-6 bottom-4 w-[3px] rounded-full"
                style={{ background: "linear-gradient(180deg, rgba(255,255,255,0.15), rgba(0,0,0,0.1))" }}
              />
            </div>
          </div>

          {/* ── Ticket Receipt ── */}
          <motion.div
            className="relative w-[72%] -mt-1 z-0"
            initial={{ maxHeight: 0, opacity: 0 }}
            animate={{ maxHeight: 600, opacity: 1 }}
            transition={{ duration: 1.5, ease: [0.25, 0.1, 0.25, 1], delay: 0.4 }}
            style={{ overflow: "hidden" }}
          >
            <div className="relative bg-[hsl(40_30%_97%)] dark:bg-[hsl(40_10%_95%)] overflow-hidden"
              style={{
                boxShadow: "0 8px 32px -8px rgba(0,0,0,0.3), 0 2px 8px -2px rgba(0,0,0,0.15), inset 0 1px 0 rgba(255,255,255,0.5)",
              }}
            >
              {/* Subtle paper texture */}
              <div className="absolute inset-0 opacity-[0.04]"
                style={{ backgroundImage: "url(\"data:image/svg+xml,%3Csvg viewBox='0 0 128 128' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='1.5' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='1'/%3E%3C/svg%3E\")" }}
                aria-hidden="true"
              />

              {/* Perforated top edge */}
              <div className="flex justify-center gap-[5px] pt-1.5 pb-1" aria-hidden="true">
                {Array.from({ length: 22 }).map((_, i) => (
                  <div key={i} className="w-[5px] h-[5px] rounded-full bg-[hsl(211_60%_16%)]" />
                ))}
              </div>

              {/* AI Badge */}
              <div className="flex items-center justify-center gap-2 pt-3 pb-2">
                <motion.div
                  className="w-9 h-9 rounded-full flex items-center justify-center shadow-md"
                  style={{
                    background: "linear-gradient(135deg, hsl(211 100% 50%), hsl(270 80% 55%))",
                  }}
                  animate={completed ? { scale: [1, 1.15, 1] } : { rotate: [0, 5, -5, 0] }}
                  transition={{ duration: completed ? 0.4 : 3, repeat: completed ? 0 : Infinity }}
                >
                  {completed ? (
                    <CheckCircle2 className="w-4.5 h-4.5 text-white" aria-hidden="true" focusable="false" />
                  ) : (
                    <Sparkles className="w-4.5 h-4.5 text-white" aria-hidden="true" focusable="false" />
                  )}
                </motion.div>
              </div>

              {/* Title area */}
              <div className="px-5 pb-2.5 text-center">
                <AnimatePresence mode="wait">
                  <motion.p
                    key={completed ? "done" : "gen"}
                    initial={{ opacity: 0, y: 4 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -4 }}
                    className="text-[9px] uppercase tracking-[0.2em] font-bold mb-1.5"
                    style={{ color: "hsl(211 60% 40%)" }}
                  >
                    {completed ? "✦ Course Ready ✦" : "✦ AI Generating ✦"}
                  </motion.p>
                </AnimatePresence>
                <h3 className="text-[13px] font-bold leading-snug line-clamp-2" style={{ color: "hsl(0 0% 15%)" }}>
                  {courseTitle}
                </h3>
              </div>

              {/* Tear-line separator */}
              <div className="mx-4 my-1 flex items-center gap-[3px]" aria-hidden="true">
                {Array.from({ length: 50 }).map((_, i) => (
                  <div key={i} className="flex-1 h-px bg-[hsl(0_0%_75%)]" />
                ))}
              </div>

              {/* Stats strip */}
              <div className="flex items-center justify-around px-4 py-2.5">
                {[
                  { icon: Layers, value: `${TICKET_SECTIONS.length}`, label: "Sections" },
                  { icon: FileText, value: `${totalPages}`, label: "Pages" },
                  { icon: Clock, value: "~60m", label: "Duration" },
                ].map((stat, i) => (
                  <div key={stat.label} className="flex items-center gap-0">
                    {i > 0 && <div className="w-px h-5 bg-[hsl(0_0%_80%)] mx-3" aria-hidden="true" />}
                    <div className="flex flex-col items-center gap-0.5">
                      <stat.icon className="w-3 h-3" style={{ color: "hsl(0 0% 55%)" }} aria-hidden="true" focusable="false" />
                      <span className="text-xs font-extrabold" style={{ color: "hsl(0 0% 15%)" }}>{stat.value}</span>
                      <span className="text-[8px] font-medium uppercase tracking-wider" style={{ color: "hsl(0 0% 50%)" }}>{stat.label}</span>
                    </div>
                  </div>
                ))}
              </div>

              {/* Tear-line separator */}
              <div className="mx-4 my-1 flex items-center gap-[3px]" aria-hidden="true">
                {Array.from({ length: 50 }).map((_, i) => (
                  <div key={i} className="flex-1 h-px bg-[hsl(0_0%_75%)]" />
                ))}
              </div>

              {/* Section reveal list */}
              <div className="px-4 py-2.5 space-y-1" role="list" aria-label="Course sections being generated">
                {TICKET_SECTIONS.map((sec, i) => {
                  const isVisible = i < visibleSections;
                  const SectionIcon = sec.icon;
                  return (
                    <motion.div
                      key={sec.title}
                      role="listitem"
                      initial={{ opacity: 0, height: 0 }}
                      animate={isVisible ? { opacity: 1, height: "auto" } : {}}
                      transition={{ duration: 0.5, ease: [0.25, 0.1, 0.25, 1] }}
                      className="overflow-hidden"
                    >
                      <div className="flex items-center gap-2 px-2.5 py-2 rounded-md my-0.5"
                        style={{ backgroundColor: "hsl(211 50% 95%)" }}
                      >
                        <div className="w-5 h-5 rounded flex items-center justify-center shrink-0"
                          style={{ backgroundColor: "hsl(211 60% 88%)" }}
                        >
                          <SectionIcon className="w-2.5 h-2.5" style={{ color: "hsl(211 100% 44%)" }} aria-hidden="true" focusable="false" />
                        </div>
                        <div className="flex-1 min-w-0">
                          <p className="text-[11px] font-semibold truncate" style={{ color: "hsl(0 0% 18%)" }}>{sec.title}</p>
                          <p className="text-[9px]" style={{ color: "hsl(0 0% 50%)" }}>{sec.pages} pages</p>
                        </div>
                        <motion.div
                          initial={{ scale: 0 }}
                          animate={isVisible ? { scale: 1 } : {}}
                          transition={{ delay: 0.25, type: "spring", stiffness: 300, damping: 15 }}
                        >
                          <CheckCircle2 className="w-3.5 h-3.5" style={{ color: "hsl(145 60% 40%)" }} aria-hidden="true" focusable="false" />
                        </motion.div>
                      </div>
                    </motion.div>
                  );
                })}

                {/* Shimmer placeholders */}
                {!completed && visibleSections < TICKET_SECTIONS.length && (
                  <div className="space-y-1" aria-hidden="true">
                    {Array.from({ length: TICKET_SECTIONS.length - visibleSections }).map((_, i) => (
                      <div key={`shimmer-${i}`} className="flex items-center gap-2 px-2.5 py-2 rounded-md">
                        <div className="w-5 h-5 rounded animate-pulse" style={{ backgroundColor: "hsl(0 0% 88%)" }} />
                        <div className="flex-1 space-y-1">
                          <div className="h-2 w-3/4 rounded animate-pulse" style={{ backgroundColor: "hsl(0 0% 85%)" }} />
                          <div className="h-1.5 w-1/3 rounded animate-pulse" style={{ backgroundColor: "hsl(0 0% 90%)" }} />
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* Tear-line separator */}
              <div className="mx-4 my-1 flex items-center gap-[3px]" aria-hidden="true">
                {Array.from({ length: 50 }).map((_, i) => (
                  <div key={i} className="flex-1 h-px bg-[hsl(0_0%_75%)]" />
                ))}
              </div>

              {/* Footer */}
              <div className="px-5 py-3 space-y-2">
                <div className="flex items-center justify-between">
                  <AnimatePresence mode="wait">
                    <motion.span
                      key={completed ? "ready" : statusIdx}
                      initial={{ opacity: 0, y: 4 }}
                      animate={{ opacity: 1, y: 0 }}
                      exit={{ opacity: 0, y: -4 }}
                      transition={{ duration: 0.2 }}
                      className="text-[10px] font-semibold"
                      style={{ color: completed ? "hsl(145 60% 35%)" : "hsl(0 0% 45%)" }}
                    >
                      {completed ? "✓ Ready to edit!" : STATUS_MESSAGES[statusIdx]}
                    </motion.span>
                  </AnimatePresence>
                  <span className="text-[11px] font-extrabold tabular-nums" style={{ color: "hsl(0 0% 15%)" }}>
                    {Math.round(progress)}%
                  </span>
                </div>

                {/* Progress bar */}
                <div className="h-1.5 w-full rounded-full overflow-hidden" style={{ backgroundColor: "hsl(0 0% 88%)" }}>
                  <motion.div
                    className="h-full rounded-full"
                    style={{
                      background: "linear-gradient(90deg, hsl(211 100% 50%), hsl(270 80% 55%), hsl(211 100% 50%))",
                      backgroundSize: "200% 100%",
                    }}
                    animate={{
                      width: `${progress}%`,
                      backgroundPosition: ["0% 0%", "100% 0%", "0% 0%"],
                    }}
                    transition={{
                      width: { duration: 0.3, ease: "easeOut" },
                      backgroundPosition: { duration: 2, repeat: Infinity, ease: "linear" },
                    }}
                  />
                </div>
              </div>

              {/* Perforated bottom */}
              <div className="flex justify-center gap-[5px] pt-1 pb-1.5" aria-hidden="true">
                {Array.from({ length: 22 }).map((_, i) => (
                  <div key={i} className="w-[5px] h-[5px] rounded-full bg-[hsl(211_60%_16%)]" />
                ))}
              </div>
            </div>

            {/* Zigzag torn bottom edge */}
            <div className="w-full h-3 overflow-hidden" aria-hidden="true">
              <svg viewBox="0 0 200 12" preserveAspectRatio="none" className="w-full h-full">
                <path
                  d={Array.from({ length: 25 }, (_, i) => `${i === 0 ? 'M' : 'L'}${i * 8},${i % 2 === 0 ? 0 : 10}`).join(' ') + ' L200,0'}
                  fill="hsl(40, 30%, 97%)"
                />
              </svg>
            </div>
          </motion.div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
